name: contacts_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  path_provider: ^2.1.2
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  freezed_annotation: ^2.4.1
  hive_flutter: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  uuid: ^4.3.3
  flutter_feather_icons: ^2.0.0+1
  fluttertoast: ^8.2.4

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

